<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLSn0hRN\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLSn0hRN/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLSn0hRN.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLSn0hRN\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLSn0hRN\App_KernelTestDebugContainer([
    'container.build_hash' => 'LSn0hRN',
    'container.build_id' => '894213f9',
    'container.build_time' => 1756281857,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLSn0hRN');
