<?php

namespace ContainerLSn0hRN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllereditProjectService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Xf77wTR.App\Controller\AdminController::editProject()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xf77wTR.App\\Controller\\AdminController::editProject()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\PortfolioProjectRepository', 'getPortfolioProjectRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'generator' => ['privates', 'App\\Service\\ProjectHtmlGenerator', 'getProjectHtmlGeneratorService', true],
            'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'repo' => 'App\\Repository\\PortfolioProjectRepository',
            'em' => '?',
            'generator' => 'App\\Service\\ProjectHtmlGenerator',
            'params' => '?',
        ]))->withContext('App\\Controller\\AdminController::editProject()', $container);
    }
}
