<?php

namespace ContainerLSn0hRN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllermessagesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.sxGqUOm.App\Controller\AdminController::messages()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sxGqUOm.App\\Controller\\AdminController::messages()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ContactMessageRepository', 'getContactMessageRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ContactMessageRepository',
        ]))->withContext('App\\Controller\\AdminController::messages()', $container);
    }
}
