<?php

namespace ContainerLSn0hRN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanProjectDescriptionsCommand_LazyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.App\Command\CleanProjectDescriptionsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\CleanProjectDescriptionsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:clean-project-descriptions', [], 'Remplace les <br> HTML dans les descriptions de projets par des retours à la ligne pour l\'édition.', false, #[\Closure(name: 'App\\Command\\CleanProjectDescriptionsCommand')] fn (): \App\Command\CleanProjectDescriptionsCommand => ($container->privates['App\\Command\\CleanProjectDescriptionsCommand'] ?? $container->load('getCleanProjectDescriptionsCommandService')));
    }
}
