<?php

namespace Container1xUdb3e;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y1MOU_DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y1MOU.d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y1MOU.d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::messages' => ['privates', '.service_locator.sxGqUOm.App\\Controller\\AdminController::messages()', 'getAdminControllermessagesService', true],
            'App\\Controller\\AdminController::deleteMessage' => ['privates', '.service_locator.jJKm4tm.App\\Controller\\AdminController::deleteMessage()', 'getAdminControllerdeleteMessageService', true],
            'App\\Controller\\AdminController::projects' => ['privates', '.service_locator.CmhsFt0.App\\Controller\\AdminController::projects()', 'getAdminControllerprojectsService', true],
            'App\\Controller\\AdminController::addProject' => ['privates', '.service_locator.gfym2J2.App\\Controller\\AdminController::addProject()', 'getAdminControlleraddProjectService', true],
            'App\\Controller\\AdminController::editProject' => ['privates', '.service_locator.Xf77wTR.App\\Controller\\AdminController::editProject()', 'getAdminControllereditProjectService', true],
            'App\\Controller\\AdminController::deleteProject' => ['privates', '.service_locator.d0XXLGQ.App\\Controller\\AdminController::deleteProject()', 'getAdminControllerdeleteProjectService', true],
            'App\\Controller\\AdminController::services' => ['privates', '.service_locator.KR517hw.App\\Controller\\AdminController::services()', 'getAdminControllerservicesService', true],
            'App\\Controller\\Api\\ContactController::contact' => ['privates', '.service_locator.lccS2KU.App\\Controller\\Api\\ContactController::contact()', 'getContactControllercontactService', true],
            'App\\Controller\\Api\\PortfolioController::getPortfolio' => ['privates', '.service_locator.CSUqEXQ.App\\Controller\\Api\\PortfolioController::getPortfolio()', 'getPortfolioControllergetPortfolioService', true],
            'App\\Controller\\Api\\RealisationApiController::getByType' => ['privates', '.service_locator.o3gXaib.App\\Controller\\Api\\RealisationApiController::getByType()', 'getRealisationApiControllergetByTypeService', true],
            'App\\Controller\\Api\\ServiceApiController::index' => ['privates', '.service_locator..wKp6bH.App\\Controller\\Api\\ServiceApiController::index()', 'getServiceApiControllerindexService', true],
            'App\\Controller\\RealisationController::index' => ['privates', '.service_locator.JxM7VLW.App\\Controller\\RealisationController::index()', 'getRealisationControllerindexService', true],
            'App\\Controller\\RealisationController::add' => ['privates', '.service_locator.zuLlZtR.App\\Controller\\RealisationController::add()', 'getRealisationControlleraddService', true],
            'App\\Controller\\RealisationController::delete' => ['privates', '.service_locator.AyPEUnP.App\\Controller\\RealisationController::delete()', 'getRealisationControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\ServiceController::index' => ['privates', '.service_locator..wKp6bH.App\\Controller\\ServiceController::index()', 'getServiceControllerindexService', true],
            'App\\Controller\\UserAdminController::index' => ['privates', '.service_locator._8VsPQl.App\\Controller\\UserAdminController::index()', 'getUserAdminControllerindexService', true],
            'App\\Controller\\UserAdminController::new' => ['privates', '.service_locator.lQAlGdR.App\\Controller\\UserAdminController::new()', 'getUserAdminControllernewService', true],
            'App\\Controller\\UserAdminController::edit' => ['privates', '.service_locator.JhNx0Mg.App\\Controller\\UserAdminController::edit()', 'getUserAdminControllereditService', true],
            'App\\Controller\\UserAdminController::delete' => ['privates', '.service_locator.P9jVROI.App\\Controller\\UserAdminController::delete()', 'getUserAdminControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:messages' => ['privates', '.service_locator.sxGqUOm.App\\Controller\\AdminController::messages()', 'getAdminControllermessagesService', true],
            'App\\Controller\\AdminController:deleteMessage' => ['privates', '.service_locator.jJKm4tm.App\\Controller\\AdminController::deleteMessage()', 'getAdminControllerdeleteMessageService', true],
            'App\\Controller\\AdminController:projects' => ['privates', '.service_locator.CmhsFt0.App\\Controller\\AdminController::projects()', 'getAdminControllerprojectsService', true],
            'App\\Controller\\AdminController:addProject' => ['privates', '.service_locator.gfym2J2.App\\Controller\\AdminController::addProject()', 'getAdminControlleraddProjectService', true],
            'App\\Controller\\AdminController:editProject' => ['privates', '.service_locator.Xf77wTR.App\\Controller\\AdminController::editProject()', 'getAdminControllereditProjectService', true],
            'App\\Controller\\AdminController:deleteProject' => ['privates', '.service_locator.d0XXLGQ.App\\Controller\\AdminController::deleteProject()', 'getAdminControllerdeleteProjectService', true],
            'App\\Controller\\AdminController:services' => ['privates', '.service_locator.KR517hw.App\\Controller\\AdminController::services()', 'getAdminControllerservicesService', true],
            'App\\Controller\\Api\\ContactController:contact' => ['privates', '.service_locator.lccS2KU.App\\Controller\\Api\\ContactController::contact()', 'getContactControllercontactService', true],
            'App\\Controller\\Api\\PortfolioController:getPortfolio' => ['privates', '.service_locator.CSUqEXQ.App\\Controller\\Api\\PortfolioController::getPortfolio()', 'getPortfolioControllergetPortfolioService', true],
            'App\\Controller\\Api\\RealisationApiController:getByType' => ['privates', '.service_locator.o3gXaib.App\\Controller\\Api\\RealisationApiController::getByType()', 'getRealisationApiControllergetByTypeService', true],
            'App\\Controller\\Api\\ServiceApiController:index' => ['privates', '.service_locator..wKp6bH.App\\Controller\\Api\\ServiceApiController::index()', 'getServiceApiControllerindexService', true],
            'App\\Controller\\RealisationController:index' => ['privates', '.service_locator.JxM7VLW.App\\Controller\\RealisationController::index()', 'getRealisationControllerindexService', true],
            'App\\Controller\\RealisationController:add' => ['privates', '.service_locator.zuLlZtR.App\\Controller\\RealisationController::add()', 'getRealisationControlleraddService', true],
            'App\\Controller\\RealisationController:delete' => ['privates', '.service_locator.AyPEUnP.App\\Controller\\RealisationController::delete()', 'getRealisationControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\ServiceController:index' => ['privates', '.service_locator..wKp6bH.App\\Controller\\ServiceController::index()', 'getServiceControllerindexService', true],
            'App\\Controller\\UserAdminController:index' => ['privates', '.service_locator._8VsPQl.App\\Controller\\UserAdminController::index()', 'getUserAdminControllerindexService', true],
            'App\\Controller\\UserAdminController:new' => ['privates', '.service_locator.lQAlGdR.App\\Controller\\UserAdminController::new()', 'getUserAdminControllernewService', true],
            'App\\Controller\\UserAdminController:edit' => ['privates', '.service_locator.JhNx0Mg.App\\Controller\\UserAdminController::edit()', 'getUserAdminControllereditService', true],
            'App\\Controller\\UserAdminController:delete' => ['privates', '.service_locator.P9jVROI.App\\Controller\\UserAdminController::delete()', 'getUserAdminControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::messages' => '?',
            'App\\Controller\\AdminController::deleteMessage' => '?',
            'App\\Controller\\AdminController::projects' => '?',
            'App\\Controller\\AdminController::addProject' => '?',
            'App\\Controller\\AdminController::editProject' => '?',
            'App\\Controller\\AdminController::deleteProject' => '?',
            'App\\Controller\\AdminController::services' => '?',
            'App\\Controller\\Api\\ContactController::contact' => '?',
            'App\\Controller\\Api\\PortfolioController::getPortfolio' => '?',
            'App\\Controller\\Api\\RealisationApiController::getByType' => '?',
            'App\\Controller\\Api\\ServiceApiController::index' => '?',
            'App\\Controller\\RealisationController::index' => '?',
            'App\\Controller\\RealisationController::add' => '?',
            'App\\Controller\\RealisationController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\ServiceController::index' => '?',
            'App\\Controller\\UserAdminController::index' => '?',
            'App\\Controller\\UserAdminController::new' => '?',
            'App\\Controller\\UserAdminController::edit' => '?',
            'App\\Controller\\UserAdminController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:messages' => '?',
            'App\\Controller\\AdminController:deleteMessage' => '?',
            'App\\Controller\\AdminController:projects' => '?',
            'App\\Controller\\AdminController:addProject' => '?',
            'App\\Controller\\AdminController:editProject' => '?',
            'App\\Controller\\AdminController:deleteProject' => '?',
            'App\\Controller\\AdminController:services' => '?',
            'App\\Controller\\Api\\ContactController:contact' => '?',
            'App\\Controller\\Api\\PortfolioController:getPortfolio' => '?',
            'App\\Controller\\Api\\RealisationApiController:getByType' => '?',
            'App\\Controller\\Api\\ServiceApiController:index' => '?',
            'App\\Controller\\RealisationController:index' => '?',
            'App\\Controller\\RealisationController:add' => '?',
            'App\\Controller\\RealisationController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\ServiceController:index' => '?',
            'App\\Controller\\UserAdminController:index' => '?',
            'App\\Controller\\UserAdminController:new' => '?',
            'App\\Controller\\UserAdminController:edit' => '?',
            'App\\Controller\\UserAdminController:delete' => '?',
        ]);
    }
}
