<?php

namespace Container1xUdb3e;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllercontactService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lccS2KU.App\Controller\Api\ContactController::contact()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lccS2KU.App\\Controller\\Api\\ContactController::contact()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailService' => ['privates', 'App\\Service\\MailService', 'getMailServiceService', true],
        ], [
            'em' => '?',
            'mailService' => 'App\\Service\\MailService',
        ]))->withContext('App\\Controller\\Api\\ContactController::contact()', $container);
    }
}
