<?php

namespace Container1xUdb3e;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanProjectDescriptionsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CleanProjectDescriptionsCommand' shared autowired service.
     *
     * @return \App\Command\CleanProjectDescriptionsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CleanProjectDescriptionsCommand.php';

        $container->privates['App\\Command\\CleanProjectDescriptionsCommand'] = $instance = new \App\Command\CleanProjectDescriptionsCommand(($container->privates['App\\Repository\\PortfolioProjectRepository'] ?? $container->load('getPortfolioProjectRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:clean-project-descriptions');
        $instance->setDescription('Remplace les <br> HTML dans les descriptions de projets par des retours à la ligne pour l\'édition.');

        return $instance;
    }
}
