<?php

namespace Container1xUdb3e;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealisationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JxM7VLW.App\Controller\RealisationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JxM7VLW.App\\Controller\\RealisationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\RealisationRepository', 'getRealisationRepositoryService', true],
            'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'repo' => 'App\\Repository\\RealisationRepository',
            'params' => '?',
        ]))->withContext('App\\Controller\\RealisationController::index()', $container);
    }
}
