<?php

namespace Container1xUdb3e;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdminControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P9jVROI.App\Controller\UserAdminController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P9jVROI.App\\Controller\\UserAdminController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', 'App\\Entity\\User', 'getUserService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'em' => '?',
            'repo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\UserAdminController::delete()', $container);
    }
}
