<?php

namespace ContainerLmKXEAs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControlleraddProjectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gfym2J2.App\Controller\AdminController::addProject()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gfym2J2.App\\Controller\\AdminController::addProject()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'generator' => ['privates', 'App\\Service\\ProjectHtmlGenerator', 'getProjectHtmlGeneratorService', true],
            'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'em' => '?',
            'generator' => 'App\\Service\\ProjectHtmlGenerator',
            'params' => '?',
        ]))->withContext('App\\Controller\\AdminController::addProject()', $container);
    }
}
