<?php

namespace ContainerLmKXEAs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerservicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KR517hw.App\Controller\AdminController::services()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KR517hw.App\\Controller\\AdminController::services()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
            'params' => '?',
        ]))->withContext('App\\Controller\\AdminController::services()', $container);
    }
}
