<?php

namespace ContainerLmKXEAs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortfolioControllergetPortfolioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CSUqEXQ.App\Controller\Api\PortfolioController::getPortfolio()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CSUqEXQ.App\\Controller\\Api\\PortfolioController::getPortfolio()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\PortfolioProjectRepository', 'getPortfolioProjectRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\PortfolioProjectRepository',
        ]))->withContext('App\\Controller\\Api\\PortfolioController::getPortfolio()', $container);
    }
}
