<?php

namespace ContainerLmKXEAs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealisationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AyPEUnP.App\Controller\RealisationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AyPEUnP.App\\Controller\\RealisationController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'realisation' => ['privates', 'App\\Entity\\Realisation', 'getRealisationService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fs' => ['privates', 'filesystem', 'getFilesystemService', true],
        ], [
            'realisation' => 'App\\Entity\\Realisation',
            'em' => '?',
            'fs' => '?',
        ]))->withContext('App\\Controller\\RealisationController::delete()', $container);
    }
}
