<?php

namespace ContainerLmKXEAs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealisationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Realisation' shared autowired service.
     *
     * @return \App\Entity\Realisation
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'Realisation.php';

        return $container->privates['App\\Entity\\Realisation'] = new \App\Entity\Realisation();
    }
}
