<?php

namespace ContainerLmKXEAs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdminControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JhNx0Mg.App\Controller\UserAdminController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JhNx0Mg.App\\Controller\\UserAdminController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', 'App\\Entity\\User', 'getUserService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'em' => '?',
            'hasher' => '?',
        ]))->withContext('App\\Controller\\UserAdminController::edit()', $container);
    }
}
