<?php

namespace ContainerWZ4fL4J;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KCR7RcmService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.KCR7Rcm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KCR7Rcm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::messages' => ['privates', '.service_locator.sxGqUOm.App\\Controller\\AdminController::messages()', 'getAdminControllermessagesService', true],
            'App\\Controller\\AdminController::deleteMessage' => ['privates', '.service_locator.jJKm4tm.App\\Controller\\AdminController::deleteMessage()', 'getAdminControllerdeleteMessageService', true],
            'App\\Controller\\AdminController::projects' => ['privates', '.service_locator.CmhsFt0.App\\Controller\\AdminController::projects()', 'getAdminControllerprojectsService', true],
            'App\\Controller\\AdminController::addProject' => ['privates', '.service_locator.gfym2J2.App\\Controller\\AdminController::addProject()', 'getAdminControlleraddProjectService', true],
            'App\\Controller\\AdminController::editProject' => ['privates', '.service_locator.Xf77wTR.App\\Controller\\AdminController::editProject()', 'getAdminControllereditProjectService', true],
            'App\\Controller\\AdminController::deleteProject' => ['privates', '.service_locator.d0XXLGQ.App\\Controller\\AdminController::deleteProject()', 'getAdminControllerdeleteProjectService', true],
            'App\\Controller\\Api\\ContactController::contact' => ['privates', '.service_locator.lccS2KU.App\\Controller\\Api\\ContactController::contact()', 'getContactControllercontactService', true],
            'App\\Controller\\Api\\PortfolioController::getPortfolio' => ['privates', '.service_locator.CSUqEXQ.App\\Controller\\Api\\PortfolioController::getPortfolio()', 'getPortfolioControllergetPortfolioService', true],
            'App\\Controller\\Api\\RealisationApiController::getByType' => ['privates', '.service_locator.o3gXaib.App\\Controller\\Api\\RealisationApiController::getByType()', 'getRealisationApiControllergetByTypeService', true],
            'App\\Controller\\Api\\ServiceController::getServices' => ['privates', '.service_locator.E.vspXI.App\\Controller\\Api\\ServiceController::getServices()', 'getServiceControllergetServicesService', true],
            'App\\Controller\\RealisationController::index' => ['privates', '.service_locator.JxM7VLW.App\\Controller\\RealisationController::index()', 'getRealisationControllerindexService', true],
            'App\\Controller\\RealisationController::add' => ['privates', '.service_locator.zuLlZtR.App\\Controller\\RealisationController::add()', 'getRealisationControlleraddService', true],
            'App\\Controller\\RealisationController::delete' => ['privates', '.service_locator.AyPEUnP.App\\Controller\\RealisationController::delete()', 'getRealisationControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:messages' => ['privates', '.service_locator.sxGqUOm.App\\Controller\\AdminController::messages()', 'getAdminControllermessagesService', true],
            'App\\Controller\\AdminController:deleteMessage' => ['privates', '.service_locator.jJKm4tm.App\\Controller\\AdminController::deleteMessage()', 'getAdminControllerdeleteMessageService', true],
            'App\\Controller\\AdminController:projects' => ['privates', '.service_locator.CmhsFt0.App\\Controller\\AdminController::projects()', 'getAdminControllerprojectsService', true],
            'App\\Controller\\AdminController:addProject' => ['privates', '.service_locator.gfym2J2.App\\Controller\\AdminController::addProject()', 'getAdminControlleraddProjectService', true],
            'App\\Controller\\AdminController:editProject' => ['privates', '.service_locator.Xf77wTR.App\\Controller\\AdminController::editProject()', 'getAdminControllereditProjectService', true],
            'App\\Controller\\AdminController:deleteProject' => ['privates', '.service_locator.d0XXLGQ.App\\Controller\\AdminController::deleteProject()', 'getAdminControllerdeleteProjectService', true],
            'App\\Controller\\Api\\ContactController:contact' => ['privates', '.service_locator.lccS2KU.App\\Controller\\Api\\ContactController::contact()', 'getContactControllercontactService', true],
            'App\\Controller\\Api\\PortfolioController:getPortfolio' => ['privates', '.service_locator.CSUqEXQ.App\\Controller\\Api\\PortfolioController::getPortfolio()', 'getPortfolioControllergetPortfolioService', true],
            'App\\Controller\\Api\\RealisationApiController:getByType' => ['privates', '.service_locator.o3gXaib.App\\Controller\\Api\\RealisationApiController::getByType()', 'getRealisationApiControllergetByTypeService', true],
            'App\\Controller\\Api\\ServiceController:getServices' => ['privates', '.service_locator.E.vspXI.App\\Controller\\Api\\ServiceController::getServices()', 'getServiceControllergetServicesService', true],
            'App\\Controller\\RealisationController:index' => ['privates', '.service_locator.JxM7VLW.App\\Controller\\RealisationController::index()', 'getRealisationControllerindexService', true],
            'App\\Controller\\RealisationController:add' => ['privates', '.service_locator.zuLlZtR.App\\Controller\\RealisationController::add()', 'getRealisationControlleraddService', true],
            'App\\Controller\\RealisationController:delete' => ['privates', '.service_locator.AyPEUnP.App\\Controller\\RealisationController::delete()', 'getRealisationControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::messages' => '?',
            'App\\Controller\\AdminController::deleteMessage' => '?',
            'App\\Controller\\AdminController::projects' => '?',
            'App\\Controller\\AdminController::addProject' => '?',
            'App\\Controller\\AdminController::editProject' => '?',
            'App\\Controller\\AdminController::deleteProject' => '?',
            'App\\Controller\\Api\\ContactController::contact' => '?',
            'App\\Controller\\Api\\PortfolioController::getPortfolio' => '?',
            'App\\Controller\\Api\\RealisationApiController::getByType' => '?',
            'App\\Controller\\Api\\ServiceController::getServices' => '?',
            'App\\Controller\\RealisationController::index' => '?',
            'App\\Controller\\RealisationController::add' => '?',
            'App\\Controller\\RealisationController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:messages' => '?',
            'App\\Controller\\AdminController:deleteMessage' => '?',
            'App\\Controller\\AdminController:projects' => '?',
            'App\\Controller\\AdminController:addProject' => '?',
            'App\\Controller\\AdminController:editProject' => '?',
            'App\\Controller\\AdminController:deleteProject' => '?',
            'App\\Controller\\Api\\ContactController:contact' => '?',
            'App\\Controller\\Api\\PortfolioController:getPortfolio' => '?',
            'App\\Controller\\Api\\RealisationApiController:getByType' => '?',
            'App\\Controller\\Api\\ServiceController:getServices' => '?',
            'App\\Controller\\RealisationController:index' => '?',
            'App\\Controller\\RealisationController:add' => '?',
            'App\\Controller\\RealisationController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
