<?php

namespace ContainerWZ4fL4J;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerprojectsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.CmhsFt0.App\Controller\AdminController::projects()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CmhsFt0.App\\Controller\\AdminController::projects()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\PortfolioProjectRepository', 'getPortfolioProjectRepositoryService', true],
            'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'repo' => 'App\\Repository\\PortfolioProjectRepository',
            'params' => '?',
        ]))->withContext('App\\Controller\\AdminController::projects()', $container);
    }
}
