<?php

namespace ContainerWZ4fL4J;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerdeleteProjectService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.d0XXLGQ.App\Controller\AdminController::deleteProject()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d0XXLGQ.App\\Controller\\AdminController::deleteProject()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\PortfolioProjectRepository', 'getPortfolioProjectRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\PortfolioProjectRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\AdminController::deleteProject()', $container);
    }
}
