<?php

namespace ContainerWZ4fL4J;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectHtmlGeneratorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\ProjectHtmlGenerator' shared autowired service.
     *
     * @return \App\Service\ProjectHtmlGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ProjectHtmlGenerator.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['App\\Service\\ProjectHtmlGenerator'])) {
            return $container->privates['App\\Service\\ProjectHtmlGenerator'];
        }

        return $container->privates['App\\Service\\ProjectHtmlGenerator'] = new \App\Service\ProjectHtmlGenerator($a, ($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
