<?php

namespace ContainerWZ4fL4J;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllergetServicesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.E.vspXI.App\Controller\Api\ServiceController::getServices()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E.vspXI.App\\Controller\\Api\\ServiceController::getServices()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\ServiceRepository',
        ]))->withContext('App\\Controller\\Api\\ServiceController::getServices()', $container);
    }
}
